name: dcat
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  http: ^1.2.1
  shelf: ^1.1.0
  shelf_router: ^1.1.0
  shelf_static: ^1.0.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
